name: Terraform State Storage Account

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target environment"
        default: "all"
        required: true
        type: choice
        options:
          - all
          - dev
          - sys
          - uat
          - prod

#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  #   AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  #   GH_PAT: ${{ secrets.READ_GITHUB_PACKAGE_PAT }}
  #   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  #   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  #   ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: |
          echo "target: ${{ github.event.inputs.target }}"

  create-storage-dev:
    if: github.event.inputs.target == 'dev'
    runs-on: ubuntu-latest
    environment: development
    env:
      ENVIRONMENT: sys
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        # with:
        #   client-id: ${{ env.ARM_CLIENT_ID }}
        #   tenant-id: ${{ env.ARM_TENANT_ID }}
        #   subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
        #   enable-AzPSSession: true

        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Az Show
        run: |
          az group list

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          cd terraform/base
          terraform init

      - name: "Terraform Validate"
        id: validate
        run: |
          cd terraform/base
          terraform validate

      - name: "Terraform Plan"
        id: plan
        run: |
          cd terraform/base
          terraform plan

      - name: "Terraform Apply"
        id: apply
        run: |
          cd terraform/base
          terraform apply -auto-approve

  create-storage-sys:
    if: github.event.inputs.target == 'sys'
    runs-on: ubuntu-latest
    environment: SystemTest
    env:
      ENVIRONMENT: sys

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        # with:
        #   client-id: ${{ env.ARM_CLIENT_ID }}
        #   tenant-id: ${{ env.ARM_TENANT_ID }}
        #   subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
        #   enable-AzPSSession: true

        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Az Show
        run: |
          az group list

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          cd terraform/base
          terraform init

      - name: "Terraform Validate"
        id: validate
        run: |
          cd terraform/base
          terraform validate

      - name: "Terraform Plan"
        id: plan
        run: |
          cd terraform/base
          terraform plan -var "environment=${{ env.ENVIRONMENT }}"

      - name: "Terraform Apply"
        id: apply
        run: |
          cd terraform/base
          terraform apply -var "environment=${{ env.ENVIRONMENT }}" -auto-approve

  create-storage-uat:
    if: github.event.inputs.target == 'uat'
    runs-on: ubuntu-latest
    environment: uat
    env:
      ENVIRONMENT: uat

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        # with:
        #   client-id: ${{ env.ARM_CLIENT_ID }}
        #   tenant-id: ${{ env.ARM_TENANT_ID }}
        #   subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
        #   enable-AzPSSession: true

        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Az Show
        run: |
          az group list

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          cd terraform/base
          terraform init

      - name: "Terraform Validate"
        id: validate
        run: |
          cd terraform/base
          terraform validate

      - name: "Terraform Plan"
        id: plan
        run: |
          cd terraform/base
          terraform plan -var "environment=${{ env.ENVIRONMENT }}"

      - name: "Terraform Apply"
        id: apply
        run: |
          cd terraform/base
          terraform apply -var "environment=${{ env.ENVIRONMENT }}" -auto-approve

  create-storage-prod:
    if: github.event.inputs.target == 'prod'
    runs-on: ubuntu-latest
    environment: Production
    env:
      ENVIRONMENT: prod

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        # with:
        #   client-id: ${{ env.ARM_CLIENT_ID }}
        #   tenant-id: ${{ env.ARM_TENANT_ID }}
        #   subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
        #   enable-AzPSSession: true

        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Az Show
        run: |
          az provider list --query "[?registrationState=='NotRegistered']" --output table

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          cd terraform/base
          terraform init

      - name: "Terraform Validate"
        id: validate
        run: |
          cd terraform/base
          terraform validate

      - name: "Terraform Plan"
        id: plan
        run: |
          cd terraform/base
          terraform plan -var "environment=${{ env.ENVIRONMENT }}"

      - name: "Terraform Apply"
        id: apply
        run: |
          cd terraform/base
          terraform apply -var "environment=${{ env.ENVIRONMENT }}" -auto-approve
